import turtle
window = turtle.Screen()

logoRMIT=turtle.Turtle()
logoRMIT.hideturtle()

logoRMIT.up()
logoRMIT.forward(100)
logoRMIT.down()

logoRMIT.circle(90,180)
logoRMIT.forward(20)
logoRMIT.left(90)
logoRMIT.forward(20)
logoRMIT.right(90)
logoRMIT.forward(40)
logoRMIT.left(90)
logoRMIT.forward(40)
logoRMIT.right(90)
logoRMIT.forward(30)
logoRMIT.left(90)
logoRMIT.forward(30)
logoRMIT.forward(30)
logoRMIT.left(90)
logoRMIT.forward(30)
logoRMIT.right(90)
logoRMIT.forward(40)
logoRMIT.left(90)
logoRMIT.forward(40)
logoRMIT.right(90)
logoRMIT.forward(20)
logoRMIT.left(90)
logoRMIT.forward(20)


window.exitonclick()