import turtle
UKflag=turtle.Turtle()
UKflag_layer2=turtle.Turtle()
AUSflag=turtle.Turtle()
Star = turtle.Turtle()
Star5 = turtle.Turtle()
window = turtle.Screen()

x=0
y=0

def draw_UKflag(x,y):
    UKflag.begin_fill()
    UKflag.color("darkblue", "darkblue")
    UKflag.fillcolor("darkblue")
    UKflag.up()
    UKflag.goto(x,y)
    UKflag.down()
    UKflag.left(90)
    for i in range(2):
        UKflag.forward(300)
        UKflag.left(90)
        UKflag.forward(600)
        UKflag.left(90)
    UKflag.end_fill()
    UKflag.begin_fill()
    UKflag.color("white", "white")
    UKflag.fillcolor("white")
    UKflag.penup()
    UKflag.left(63.50)
    UKflag.forward(670)
    UKflag.pendown()
    UKflag.left(180 - 63.50)
    UKflag.forward(30)
    UKflag.left(63.50)
    UKflag.forward(602)
    UKflag.left(26.50)
    UKflag.forward(61)
    UKflag.left(90)
    UKflag.forward(30)
    UKflag.left(63.50)
    UKflag.forward(605)
    UKflag.left(26.50)
    UKflag.forward(61)
    UKflag.end_fill()

    UKflag.up()
    UKflag.backward(600)
    UKflag.left(26.6)
    UKflag.forward(670)
    UKflag.down()
    UKflag.begin_fill()
    UKflag.fillcolor("white")
    UKflag.left(180 - 26.50)
    UKflag.forward(60)
    UKflag.left(26.50)
    UKflag.forward(605)
    UKflag.left(63.50)
    UKflag.forward(29)
    UKflag.left(90)
    UKflag.forward(60)
    UKflag.left(26.50)
    UKflag.forward(603.31)
    UKflag.left(63.50)
    UKflag.forward(30)
    UKflag.end_fill()


    UKflag_layer2.up()
    UKflag_layer2.goto(x-300,y+150)
    UKflag_layer2.right(90)
    UKflag_layer2.forward(150)
    UKflag_layer2.down()
    UKflag_layer2.right(90)
    UKflag_layer2.begin_fill()
    UKflag_layer2.fillcolor("white")
    for i in range(2):
        UKflag_layer2.forward(50)
        UKflag_layer2.right(90)
        UKflag_layer2.forward(100)
        UKflag_layer2.left(90)
        UKflag_layer2.forward(250)
        UKflag_layer2.right(90)
        UKflag_layer2.forward(100)
        UKflag_layer2.right(90)
        UKflag_layer2.forward(250)
        UKflag_layer2.left(90)
        UKflag_layer2.forward(100)
        UKflag_layer2.right(90)
        UKflag_layer2.forward(50)
    UKflag_layer2.end_fill()

    UKflag_layer2.begin_fill()
    UKflag_layer2.fillcolor("red")
    for i in range(2):
        UKflag_layer2.forward(30)
        UKflag_layer2.right(90)
        UKflag_layer2.forward(120)
        UKflag_layer2.left(90)
        UKflag_layer2.forward(270)
        UKflag_layer2.right(90)
        UKflag_layer2.forward(60)
        UKflag_layer2.right(90)
        UKflag_layer2.forward(270)
        UKflag_layer2.left(90)
        UKflag_layer2.forward(120)
        UKflag_layer2.right(90)
        UKflag_layer2.forward(30)
    UKflag_layer2.end_fill()


    UKflag_layer2.up()
    UKflag_layer2.forward(300)
    UKflag_layer2.down()
    UKflag_layer2.right(90)
    for i in range(2):
        UKflag_layer2.begin_fill()
        UKflag_layer2.fillcolor("red")

        UKflag_layer2.right(63.50)
        UKflag_layer2.forward(225)
        UKflag_layer2.right(26.50)
        UKflag_layer2.forward(40)
        UKflag_layer2.right(180-26.50)
        UKflag_layer2.forward(225)
        UKflag_layer2.right(26.50)
        UKflag_layer2.forward(40)
        UKflag_layer2.end_fill()
        UKflag_layer2.backward(600)
        UKflag_layer2.begin_fill()
        UKflag_layer2.fillcolor("red")
        UKflag_layer2.right(26.5)
        UKflag_layer2.forward(225)
        UKflag_layer2.right(180-26.50)
        UKflag_layer2.forward(40)
        UKflag_layer2.right(26.5)
        UKflag_layer2.forward(180)
        UKflag_layer2.right(63.5)
        UKflag_layer2.forward(20)
        UKflag_layer2.end_fill()
        UKflag_layer2.backward(300)

def draw_star_flag(size):
    Star.right(180-154.25+12.875)
    Star.up()
    Star.backward(size/2)
    Star.down()
    Star.begin_fill()
    Star.color("white", "white")
    Star.fillcolor("white")
    Star.left(12.875)
    for i in range(7):
        Star.forward(size)
        Star.right(154.25)
    Star.end_fill()
    Star.right(180 - 154.25)

def draw_AUSflag(x,y):
    AUSflag.goto(x - 600, y + 300)
    AUSflag.right(90)
    AUSflag.begin_fill()
    AUSflag.fillcolor("darkblue")
    for i in range(2):
        AUSflag.forward(600)
        AUSflag.left(90)
        AUSflag.forward(1200)
        AUSflag.left(90)
    AUSflag.end_fill()
    draw_UKflag(x, y)
    Star.up()
    Star.goto(x - 300, y - 150)
    Star.down()
    draw_star_flag(150)

    Star.up()
    Star.goto(x+300, y + 200)
    Star.down()
    draw_star_flag(600/8)

    Star.up()
    Star.goto(x + 300, y - 200)
    Star.down()
    draw_star_flag(600 / 8)

    Star.up()
    Star.goto(x + 150, y + 45)
    Star.down()
    draw_star_flag(600 / 8)

    Star.up()
    Star.goto(x + 450, y + 75)
    Star.down()
    draw_star_flag(600 / 8)

    Star5.up()
    Star5.goto(x + 400, y - 10)
    Star5.down()
    Star5.begin_fill()
    Star5.color("white", "white")
    Star5.fillcolor("white")
    Star5.up()
    Star5.backward(20)
    Star5.down()

    for i in range(5):
        Star5.forward(40)
        Star5.right(144)
    Star5.end_fill()

draw_AUSflag(x,y)
window.exitonclick()