import turtle
UKflag=turtle.Turtle()
UKflag_layer2=turtle.Turtle()
window = turtle.Screen()


def draw_UKflag():
    UKflag.begin_fill()
    UKflag.color("darkblue", "darkblue")
    UKflag.fillcolor("darkblue")
    UKflag.up()
    UKflag.goto(300,-150)
    UKflag.down()
    UKflag.left(90)
    for i in range(2):
        UKflag.forward(300)
        UKflag.left(90)
        UKflag.forward(600)
        UKflag.left(90)
    UKflag.end_fill()
    UKflag.begin_fill()
    UKflag.color("white", "white")
    UKflag.fillcolor("white")
    UKflag.penup()
    UKflag.left(63.50)
    UKflag.forward(670)
    UKflag.pendown()
    UKflag.left(180 - 63.50)
    UKflag.forward(30)
    UKflag.left(63.50)
    UKflag.forward(602)
    UKflag.left(26.50)
    UKflag.forward(61)
    UKflag.left(90)
    UKflag.forward(30)
    UKflag.left(63.50)
    UKflag.forward(605)
    UKflag.left(26.50)
    UKflag.forward(61)
    UKflag.end_fill()

    UKflag.up()
    UKflag.backward(600)
    UKflag.left(26.6)
    UKflag.forward(670)
    UKflag.down()
    UKflag.begin_fill()
    UKflag.fillcolor("white")
    UKflag.left(180 - 26.50)
    UKflag.forward(60)
    UKflag.left(26.50)
    UKflag.forward(605)
    UKflag.left(63.50)
    UKflag.forward(29)
    UKflag.left(90)
    UKflag.forward(60)
    UKflag.left(26.50)
    UKflag.forward(603.31)
    UKflag.left(63.50)
    UKflag.forward(30)
    UKflag.end_fill()

    UKflag_layer2.begin_fill()
    UKflag_layer2.fillcolor("white")
    UKflag_layer2.up()
    UKflag_layer2.right(90)
    UKflag_layer2.forward(150)
    UKflag_layer2.down()
    UKflag_layer2.right(90)
    for i in range(2):
        UKflag_layer2.forward(50)
        UKflag_layer2.right(90)
        UKflag_layer2.forward(100)
        UKflag_layer2.left(90)
        UKflag_layer2.forward(250)
        UKflag_layer2.right(90)
        UKflag_layer2.forward(100)
        UKflag_layer2.right(90)
        UKflag_layer2.forward(250)
        UKflag_layer2.left(90)
        UKflag_layer2.forward(100)
        UKflag_layer2.right(90)
        UKflag_layer2.forward(50)
    UKflag_layer2.end_fill()

    UKflag_layer2.begin_fill()
    UKflag_layer2.fillcolor("red")
    for i in range(2):
        UKflag_layer2.forward(30)
        UKflag_layer2.right(90)
        UKflag_layer2.forward(120)
        UKflag_layer2.left(90)
        UKflag_layer2.forward(270)
        UKflag_layer2.right(90)
        UKflag_layer2.forward(60)
        UKflag_layer2.right(90)
        UKflag_layer2.forward(270)
        UKflag_layer2.left(90)
        UKflag_layer2.forward(120)
        UKflag_layer2.right(90)
        UKflag_layer2.forward(30)
    UKflag_layer2.end_fill()


    UKflag_layer2.up()
    UKflag_layer2.forward(300)
    UKflag_layer2.down()
    UKflag_layer2.right(90)
    for i in range(2):
        UKflag_layer2.begin_fill()
        UKflag_layer2.fillcolor("red")

        UKflag_layer2.right(63.50)
        UKflag_layer2.forward(225)
        UKflag_layer2.right(26.50)
        UKflag_layer2.forward(40)
        UKflag_layer2.right(180-26.50)
        UKflag_layer2.forward(225)
        UKflag_layer2.right(26.50)
        UKflag_layer2.forward(40)
        UKflag_layer2.end_fill()
        UKflag_layer2.backward(600)
        UKflag_layer2.begin_fill()
        UKflag_layer2.fillcolor("red")
        UKflag_layer2.right(26.5)
        UKflag_layer2.forward(225)
        UKflag_layer2.right(180-26.50)
        UKflag_layer2.forward(40)
        UKflag_layer2.right(26.5)
        UKflag_layer2.forward(180)
        UKflag_layer2.right(63.5)
        UKflag_layer2.forward(20)
        UKflag_layer2.end_fill()
        UKflag_layer2.backward(300)

draw_UKflag()
window.exitonclick()